jenkins:
  numExecutors: 4
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Job/Build:dev"
        - "Job/Cancel:dev"
        - "Job/Read:dev"
        - "Job/Workspace:dev"
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
        - "Run/Replay:dev"
        - "Run/Update:dev"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_ID}
          password: ${JENKINS_ADMIN_PASSWORD}
  disabledAdministrativeMonitors:
  - "org.jenkinsci.plugins.matrixauth.AmbiguityMonitor"
  - "jenkins.diagnostics.ControllerExecutorsNoAgents"
  - "jenkins.diagnostics.RootUrlNotSetMonitor"
  - "jenkins.security.QueueItemAuthenticatorMonitor"
  - "jenkins.security.ResourceDomainRecommendation"
  - "jenkins.security.s2m.MasterKillSwitchWarning"

unclassified:
  login-theme-plugin:
    footer: |
      <script>
        var logEl = document.querySelector("#loginIntroDefault .logo img");
        var titleEl = document.querySelector("#loginIntroDefault h1");
        
        logEl['src'] = 'https://upload.wikimedia.org/wikipedia/commons/e/e4/Robot-framework-logo.png'
        titleEl.textContent = "Welcome to Josef's Pipelines"

      </script>
  simple-theme-plugin:
    elements:
    - cssText:
        text: |-
            .logo img {
                content: url("/userContent/layout/logo.svg");
            }
            .logo:after {
                content: "Josef's Pipelines";
                color: white;
                font-family: sans-serif;
                font-weight: 600;
                margin-left: 25px;
                margin-right: 12px;
                line-height: 40px;
            }
            #jenkins-name-icon {
                display: none;
            }
          
  themeManager:
    disableUserThemes: false
    theme: "dark"

jobs:
  - file: /opt/deploy/dsl/ansible.groovy
  - file: /opt/deploy/dsl/rf.groovy